export default Object.freeze({
	PEAR_HOME_SCREEN: "PearHomeScreen",
	DNS_HOME_SCREEN: "DnsHomeScreen",
	WELCOME_FIRST_SCREEN: "WelcomeScreenFirst",
	WELCOME_SECOND_SCREEN: "WelcomeScreensecond",
	WELCOME_THIRD_SCREEN: "WelcomeScreenThird",
	REGISTER_FIRST_SCREEN: "RegisterFirst",
	REGISTER_SECOND_SCREEN: "RegisterSecond",
	LOGIN_SCREEN: "LoginScreen",
	INSTRUCTOR_DETAILS: "Instructor",
	TEACHERS_SCREEN: "TeachersScreen",
	COURSES_SCREEN: "CoursesScreen",
	STACK_NAVIGATION: "StackNavigation",
	COURSE_DETAILS: "CourseDetails",
	BOTTOM_TAPS_NAVIGATOR: "BottomTabsNavigator",
});
