import { createSlice } from "@reduxjs/toolkit";

const courseData = [
  {
    id: 1,
    image: require("../assets/pearImages/all-course-1.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Supply Chain Mangement",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 2,
    image: require("../assets/pearImages/all-course-2.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "HR Mangement",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 3,
    image: require("../assets/pearImages/all-course-3.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Frontend Track",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 4,
    image: require("../assets/pearImages/all-course-1.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Backend Track",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 5,
    image: require("../assets/pearImages/all-course-2.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "JavaScript",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 6,
    image: require("../assets/pearImages/all-course-3.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "React Js",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 7,
    image: require("../assets/pearImages/all-course-1.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Redux",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 8,
    image: require("../assets/pearImages/all-course-2.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Angular",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 9,
    image: require("../assets/pearImages/all-course-3.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Vue JS",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 10,
    image: require("../assets/pearImages/all-course-1.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "ASP.net core",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 11,
    image: require("../assets/pearImages/all-course-2.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "HTML / HTML5",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 12,
    image: require("../assets/pearImages/all-course-3.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "CSS / CSS3",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 13,
    image: require("../assets/pearImages/all-course-1.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "React Native",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 14,
    image: require("../assets/pearImages/all-course-2.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Flutter",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 15,
    image: require("../assets/pearImages/all-course-3.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Bootstrap",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 16,
    image: require("../assets/pearImages/all-course-1.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Graphic Design",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 17,
    image: require("../assets/pearImages/all-course-2.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Machine Learning",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
  {
    id: 18,
    image: require("../assets/pearImages/all-course-3.png"),
    instractourName: "By Dr/Ahmec Selim",
    courseName: "Sales",
    courseDescription: "HR-Human Rescores Management Lorem Aps Leand",
    courseDutation: "24 Hours",
  },
];

const initState = { courseData };
const courseCardInfoSlice = createSlice({
  name: "courseCardInfo",
  initialState: initState,
  reducers: {},
});

// Action creators are generated for each case reducer function
// export const { id } = courseCardInfoSlice.actions;

export default courseCardInfoSlice.reducer;